camera:
  ros__parameters:
    # use camera as video resource
    # type: 1
    # use video as video re ghiufycdxAszdsource
    type: 2
    resource: '/home/nvidia/Downloads/red_exposure.mp4'
    inputAngle : 30.0
    inputScale: 0.20
    use_image_qos: false
